---
apiVersion: v1 # this is headless service
kind: Service
metadata: 
   name: mongodb-headless
   namespace: roboshop
   labels:
     component: mongodb
     project: roboshop
     tier: database
spec:
    clusterIP: None
    selector:
      component: mongodb
      project: roboshop
      tier: database
ports:
 - protocol: TCP
   port: 27017
   targetPort: 27017 
---
apiVersion: v1 # normal service
kind: Service
metadata:
   name: mongodb
   namespace: roboshop
   labels:
     component: mongodb
     project: roboshop
     tier: database
spec:
  selector:
    component: mongodb
    project: roboshop
    tier: database
ports:
- protocol: TCP
  port: 27017
  targetPort: 27017
---
apiVersion: apps/v1 
kind: StatefulSet
metadata: 
   name: mongodb
   namespace: roboshop
   labels:
     component: mongodb
     project: roboshop
     tier: database
spec:
   selector: 
   matachLabels: # has to match spec, template, metadata.labels
     component: mongodb
     project: roboshop
     tier: database
   ServiceName: "mongodb-headless" # this should be headless service
   replicas: 3
   template: # this is pod definition
     metadata:
        labels:
           component: mongodb
           project: roboshop
           tier: database
     spec:
       containers:
       - name: mongodb
         image: shirisha104/mongodb:v1
         volumeMounts:
         - name: mongodb-data
           mountPath: /data/db # mongodb database dirctory
      # this is nothing but PVC, you can directly create here
     volumeClaimTemplates: 
     - metadata: 
          name: mongodb-data
       spec:
       accessModes: ["ReadWriteOnce"]
       storageClassName: "roboshop-ebs"
       resources:
         requests:
           storage: 2Gi


  